# Generated by Django 3.2.9 on 2021-12-08 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('selects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('address', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=1)),
                ('homepage', models.BooleanField(default=False)),
                ('positionX', models.FloatField()),
                ('positionY', models.FloatField()),
                ('done', models.BooleanField(default=False)),
                ('inProgress', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('garage', models.BooleanField(default=False)),
                ('pets', models.BooleanField(default=False)),
                ('deposit', models.IntegerField(default=0)),
                ('pay_period', models.IntegerField(default=0)),
                ('min_period', models.IntegerField(default=0)),
                ('available', models.DateField(blank=True, default=None, null=True)),
                ('price_allow', models.BooleanField(default=False)),
                ('level', models.IntegerField(default=0)),
                ('size_out', models.IntegerField(default=0)),
                ('size_all', models.IntegerField(default=0)),
                ('paper', models.BooleanField(default=False)),
                ('cameras', models.BooleanField(default=False)),
                ('alarm', models.BooleanField(default=False)),
                ('storage', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('armed_door', models.BooleanField(default=False)),
                ('phone', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('basement', models.BooleanField(default=False)),
                ('updated', models.BooleanField(default=False)),
                ('invoice_included', models.BooleanField(default=False)),
                ('stockroom', models.BooleanField(default=False)),
                ('from_river', models.IntegerField(default=0)),
                ('automatic_door', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('building_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.building_material')),
                ('building_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.building_type')),
                ('building_usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.building_usage')),
                ('estate_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.estatetype')),
                ('floor_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.floor_type')),
                ('floors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.floors')),
                ('garage_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.garage_type')),
                ('heating_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.heatingtype')),
                ('kitchen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.kitchen')),
                ('new_or_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.new_or_used')),
                ('object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.object_type')),
                ('road', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.road')),
                ('rooms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.rooms')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.status')),
                ('toilets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.toilet')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.type')),
                ('vehicle_capacity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.vehicle_capacity')),
                ('year_of_build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.year_of_build')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
