# Generated by Django 4.0 on 2021-12-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_bathrooms_alter_product_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='positionX',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='positionY',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
