# Generated by Django 4.0 on 2021-12-16 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_positionx_alter_product_positiony'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='building_material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='building_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='building_usage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='estate_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='floor_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='floors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='garage_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='heating_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new_or_used',
        ),
        migrations.RemoveField(
            model_name='product',
            name='object_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='road',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='toilets',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vehicle_capacity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='year_of_build',
        ),
    ]
