# Generated by Django 4.0 on 2021-12-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_building_material_product_building_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='level',
        ),
        migrations.AlterField(
            model_name='product',
            name='positionX',
            field=models.FloatField(default=44.7768313),
        ),
        migrations.AlterField(
            model_name='product',
            name='positionY',
            field=models.FloatField(default=17.1933091),
        ),
    ]
