# Generated by Django 4.0 on 2021-12-21 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selects', '0004_floor'),
        ('products', '0008_remove_product_level_alter_product_positionx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='floor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.floor'),
        ),
    ]
