# Generated by Django 4.0 on 2021-12-21 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selects', '0005_bathrooms_bedrooms_toiletnumber'),
        ('products', '0009_product_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='toilet_number',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.toiletnumber'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bathrooms',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.bathrooms'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bedrooms',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selects.bedrooms'),
        ),
    ]
