# Generated by Django 4.0 on 2021-12-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_bathrooms_alter_product_bedrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bedrooms',
        ),
    ]
