version: "3"

services:
  backend:
    build:
      context: ./backend/core
    command: /bin/ash -c "python3 manage.py makemigrations && python3 manage.py migrate && gunicorn core.wsgi --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - media:/backend/media
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
    command: /bin/ash -c "npm run dev"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - /frontend/.next
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - media:/media
    depends_on:
      - frontend
  db:
    # platform: linux/amd64
    # image: mysql:5.7.22
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_DATABASE: everest
      MYSQL_USER: everest
      MYSQL_PASSWORD: everest123
      MYSQL_ROOT_PASSWORD: test333
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306

volumes:
  media:
